version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
     container_name: dbwpm
     image: mysqllatch
     build: ./db
     volumes:
       - db_data:/var/lib/mysql:ro
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mysqlroot
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: mysqlroot
       LATCHAPPID: 2hMPhcVwnGVwBEju4agR
       LATCHSECRET: kXJt9bpPvHtBCfg2xCEKNFZwXN4s9bR7hzgXgBwq


  wordpress:
     container_name: wpm
     build: ./wp
     depends_on:
       - db
     image: wplatch
     #image: wordpress:latest
     restart: always
     volumes:
       - ./wordpress:/var/www/html/wordpress:ro
     expose:
       - "80"
     environment:
       - WORDPRESS_DB_HOST:"wordpress"
       - WORDPRESS_DB_USER:"root"
       - WORDPRESS_DB_PASSWORD:"mysqlroot"
       - VIRTUAL_HOST=softweel.com,www.softweel.com
       - LETSENCRYPT_HOST=softweel.com,www.softweel.com
       - LETSENCRYPT_EMAIL=resourceldg@gmail.com

     links:
      - db:db
 

volumes: 
  certs:
  html:
  vhostd:
  db_data:
  wordpress:
